/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as ApiStreamSessionIdRouteImport } from './routes/api.stream.$sessionId'
import { Route as ApiInterruptSessionIdRouteImport } from './routes/api.interrupt.$sessionId'
import { Route as ApiFileSessionIdRouteImport } from './routes/api.file.$sessionId'
import { Route as ApiDiffSessionIdChangeIdRouteImport } from './routes/api.diff.$sessionId.$changeId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamSessionIdRoute = ApiStreamSessionIdRouteImport.update({
  id: '/api/stream/$sessionId',
  path: '/api/stream/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterruptSessionIdRoute = ApiInterruptSessionIdRouteImport.update({
  id: '/api/interrupt/$sessionId',
  path: '/api/interrupt/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileSessionIdRoute = ApiFileSessionIdRouteImport.update({
  id: '/api/file/$sessionId',
  path: '/api/file/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffSessionIdChangeIdRoute =
  ApiDiffSessionIdChangeIdRouteImport.update({
    id: '/api/diff/$sessionId/$changeId',
    path: '/api/diff/$sessionId/$changeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/file/$sessionId': typeof ApiFileSessionIdRoute
  '/api/interrupt/$sessionId': typeof ApiInterruptSessionIdRoute
  '/api/stream/$sessionId': typeof ApiStreamSessionIdRoute
  '/api/diff/$sessionId/$changeId': typeof ApiDiffSessionIdChangeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/file/$sessionId': typeof ApiFileSessionIdRoute
  '/api/interrupt/$sessionId': typeof ApiInterruptSessionIdRoute
  '/api/stream/$sessionId': typeof ApiStreamSessionIdRoute
  '/api/diff/$sessionId/$changeId': typeof ApiDiffSessionIdChangeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/file/$sessionId': typeof ApiFileSessionIdRoute
  '/api/interrupt/$sessionId': typeof ApiInterruptSessionIdRoute
  '/api/stream/$sessionId': typeof ApiStreamSessionIdRoute
  '/api/diff/$sessionId/$changeId': typeof ApiDiffSessionIdChangeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/session/$sessionId'
    | '/api/file/$sessionId'
    | '/api/interrupt/$sessionId'
    | '/api/stream/$sessionId'
    | '/api/diff/$sessionId/$changeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/session/$sessionId'
    | '/api/file/$sessionId'
    | '/api/interrupt/$sessionId'
    | '/api/stream/$sessionId'
    | '/api/diff/$sessionId/$changeId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/session/$sessionId'
    | '/api/file/$sessionId'
    | '/api/interrupt/$sessionId'
    | '/api/stream/$sessionId'
    | '/api/diff/$sessionId/$changeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  ApiFileSessionIdRoute: typeof ApiFileSessionIdRoute
  ApiInterruptSessionIdRoute: typeof ApiInterruptSessionIdRoute
  ApiStreamSessionIdRoute: typeof ApiStreamSessionIdRoute
  ApiDiffSessionIdChangeIdRoute: typeof ApiDiffSessionIdChangeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$sessionId': {
      id: '/api/stream/$sessionId'
      path: '/api/stream/$sessionId'
      fullPath: '/api/stream/$sessionId'
      preLoaderRoute: typeof ApiStreamSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interrupt/$sessionId': {
      id: '/api/interrupt/$sessionId'
      path: '/api/interrupt/$sessionId'
      fullPath: '/api/interrupt/$sessionId'
      preLoaderRoute: typeof ApiInterruptSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$sessionId': {
      id: '/api/file/$sessionId'
      path: '/api/file/$sessionId'
      fullPath: '/api/file/$sessionId'
      preLoaderRoute: typeof ApiFileSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diff/$sessionId/$changeId': {
      id: '/api/diff/$sessionId/$changeId'
      path: '/api/diff/$sessionId/$changeId'
      fullPath: '/api/diff/$sessionId/$changeId'
      preLoaderRoute: typeof ApiDiffSessionIdChangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  ApiFileSessionIdRoute: ApiFileSessionIdRoute,
  ApiInterruptSessionIdRoute: ApiInterruptSessionIdRoute,
  ApiStreamSessionIdRoute: ApiStreamSessionIdRoute,
  ApiDiffSessionIdChangeIdRoute: ApiDiffSessionIdChangeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
